restart_file: .na
start_datetime: 2022-12-01 00:00:00
end_datetime: .na
forecast_start_datetime: 2023-08-01 00:00:00
forecast_horizon: 34.0
sim_name: feea_test
configure_flare: configure_flare_feea.yml
configure_obs: observation_processing_feea.yml
use_s3: TRUE
